manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
      a1:  0
      a2: -0.042
      b:   0.0
      c1:  0.3991
      c2:  0.350
      c3:  0.351
      c4:  0.082
  opw_kinematics_joint_offsets: [0.0, 0.0, deg(-90.0), 0.0, 0.0, 0.0]
  opw_kinematics_joint_sign_corrections: [1, 1, 1, 1, 1, 1]
